### ISSUE TITLE
Linker Error during MSVC2015 And Qt 5.7 Build

### ISSUE THREAD

**Issue by Pavel-Melnikov** [vlc-qt/vlc-qt#173]
I' m adding QWidget on QMainWindow and transforming it to VlcWidgetVideo . Unfortunately, I receive Linker errors on some VlcWidgetVideo functions. Here is my output:

mainwindow.obj:-1: ошибка: LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __thiscall VlcWidgetVideo::metaObject(void)const " (?metaObject@VlcWidgetVideo@@UBEPBUQMetaObject@@XZ)
mainwindow.obj:-1: ошибка: LNK2001: unresolved external symbol "public: virtual int __thiscall VlcWidgetVideo::qt_metacall(enum QMetaObject::Call,int,void * *)" (?qt_metacall@VlcWidgetVideo@@UAEHW4Call@QMetaObject@@HPAPAX@Z)
mainwindow.obj:-1: ошибка: LNK2001: unresolved external symbol "public: virtual int __thiscall VlcWidgetVideo::qt_metacall(enum QMetaObject::Call,int,void * *)" (?qt_metacall@VlcWidgetVideo@@UAEHW4Call@QMetaObject@@HPAPAX@Z)
mainwindow.obj:-1: ошибка: LNK2001: unresolved external symbol "public: virtual void * __thiscall VlcWidgetVideo::qt_metacast(char const *)" (?qt_metacast@VlcWidgetVideo@@UAEPAXPBD@Z)
mainwindow.obj:-1: ошибка: LNK2001: unresolved external symbol "public: virtual void __thiscall VlcWidgetVideo::release(void)" (?release@VlcWidgetVideo@@UAEXXZ)
mainwindow.obj:-1: ошибка: LNK2001: unresolved external symbol "public: virtual unsigned int __thiscall VlcWidgetVideo::request(void)" (?request@VlcWidgetVideo@@UAEIXZ)

request and release are handling video frames, so there may be an issue somewhere   
in VlcVideoDelegate due to these functions are virtual

**Comment by ntadej** [comment]
I need more information:
 - which OS and compiler
 - which VLC-Qt version, self built or not

**Comment by Pavel-Melnikov** [comment]
I have set MSVC2013 x86 compiler,  OS -  Windows 8.1 x64 
VLC-QT 1.0, Just have downloaded and linked static libraries 
building with qmake in debug mode
Now I have fixed link errors, but an app crashes. I will check later what could cause an issue

**Comment by ntadej** [comment]
Make sure you do not mix:
 - Qt versions
 - compiler versions
 - debug and release builds

So always build your project with same Qt and compiler version as VLC-Qt, also both in release or debug mode.

I'm closing this for now as it seems you encounter the same issue as many other users with this mixing.

**Comment by kheaactua** [comment]
Just to be confident that I'm not mixing Qt, compiler, or build types, I deleted everything and rebuild, but still get this error.

I'm trying to build VLCQt 1.1.0, using msvc2013, Qt 5.9.1, and Release builds.

The project builds, and with a tweak in the `config/Dependencies.cmake:63` to properly detect `LIBVLC_BIN_DIR`, the project installs.  But when I try to link against it, I get

```text
main.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl VlcQmlPlayer::metaObject(void)const " (?metaObject@VlcQmlPlayer@@UEBAPEBUQMetaObject@@XZ) [C:\Users\mrussell\workspace\project\build-Release\app\app.vcxproj]
main.obj : error LNK2001: unresolved external symbol "public: virtual void * __cdecl VlcQmlPlayer::qt_metacast(char const *)" (?qt_metacast@VlcQmlPlayer@@UEAAPEAXPEBD@Z) [C:\Users\mrussell\workspace\project\build-release\app\app.vcxproj]
main.obj : error LNK2001: unresolved external symbol "public: virtual int __cdecl VlcQmlPlayer::qt_metacall(enum QMetaObject::Call,int,void * *)" (?qt_metacall@VlcQmlPlayer@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z) [C:\Users\mrussell\workspace\project\build-Release\app\app.vcxproj]
main.obj : error LNK2019: unresolved external symbol "public: __cdecl VlcQmlPlayer::VlcQmlPlayer(class QObject *)" (??0VlcQmlPlayer@@QEAA@PEAVQObject@@@Z) referenced in function "void __cdecl QQmlPrivate::createInto<class VlcQmlPlayer>(void *)" (??$createInto@VVlcQmlPlayer@@@QQmlPrivate@@YAXPEAX@Z) [C:\Users\mrussell\workspace\project\build-Release\app\app.vcxproj]
main.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl VlcQmlPlayer::~VlcQmlPlayer(void)" (??1VlcQmlPlayer@@UEAA@XZ) referenced in function "public: virtual __cdecl QQmlPrivate::QQmlElement<class VlcQmlPlayer>::~QQmlElement<class VlcQmlPlayer>(void)" (??1?$QQmlElement@VVlcQmlPlayer@@@QQmlPrivate@@UEAA@XZ) [C:\Users\mrussell\workspace\project\build-Release\app\app.vcxproj]
main.obj : error LNK2019: unresolved external symbol "public: static struct QMetaObject const VlcQmlPlayer::staticMetaObject" (?staticMetaObject@VlcQmlPlayer@@2UQMetaObject@@B) referenced in function "int __cdecl qRegisterNormalizedMetaType<class VlcQmlPlayer *>(class QByteArray const &,class VlcQmlPlayer * *,enum QtPrivate::MetaTypeDefinedHelper<class VlcQmlPlayer *,1>::DefinedType)" (??$qRegisterNormalizedMetaType@PEAVVlcQmlPlayer@@@@YAHAEBVQByteArray@@PEAPEAVVlcQmlPlayer@@W4DefinedType@?$MetaTypeDefinedHelper@PEAVVlcQmlPlayer@@$00@QtPrivate@@@Z) [C:\Users\mrussell\workspace\project\build-Release\app\app.vcxproj]
C:\Users\mrussell\workspace\project\build-Release\app\Release\app.exe : fatal error LNK1120: 6 unresolved externals [C:\Users\mrussell\workspace\project\build-Release\app\app.vcxproj]
```
